# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/LeTien/python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 571)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 751, 609))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(520, 480, 201, 31))
        self.frame.setStyleSheet("border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.label_3.setStyleSheet("    color: #a0a0a0; /* Màu chữ xám nhạt */\n"
"    font-size: 14px;\n"
"    font-weight: normal;")
        self.label_3.setObjectName("label_3")
        self.btn_register = QtWidgets.QPushButton(parent=self.frame)
        self.btn_register.setGeometry(QtCore.QRect(140, 0, 71, 31))
        self.btn_register.setStyleSheet("    color: #ffa14a; /* Màu cam */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    cursor: pointer;\n"
"border: none;")
        self.btn_register.setObjectName("btn_register")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 430, 381, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.google = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.google.setStyleSheet("background-color: #ffffff; /* Nền trắng */\n"
"    color: #000000; /* Chữ màu đen */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s ease, border-color 0.3s ease;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/LeTien/python-app/ui/../img/download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.google.setIcon(icon)
        self.google.setObjectName("google")
        self.horizontalLayout_2.addWidget(self.google)
        self.facebook = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.facebook.setStyleSheet("background-color: #ffffff; /* Nền trắng */\n"
"    color: #000000; /* Chữ màu đen */\n"
"    border: 1px solid #cccccc; /* Viền xám nhạt */\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s ease, border-color 0.3s ease;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/LeTien/python-app/ui/../img/download (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.facebook.setIcon(icon1)
        self.facebook.setObjectName("facebook")
        self.horizontalLayout_2.addWidget(self.facebook)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 380, 83, 71))
        self.label_4.setStyleSheet("    color: #a0a0a0; /* Màu xám nhạt */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    background: transparent;")
        self.label_4.setObjectName("label_4")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(350, 350, 364, 40))
        self.btn_login.setStyleSheet("background-color: rgb(249, 79, 47);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    cursor: pointer;\n"
"    transition: background-color 0.3s ease;")
        self.btn_login.setObjectName("btn_login")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(-10, 60, 350, 433))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/LeTien/python-app/ui/../img/12.png"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 50, 201, 61))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/LeTien/python-app/ui/../img/Shopee-logo-2.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 110, 181, 51))
        self.label_5.setStyleSheet("    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #000000; /* Màu đen */\n"
"    margin-bottom: 8px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 150, 180, 17))
        self.label_6.setStyleSheet("\n"
"    font-size: 14px;\n"
"    font-weight: normal;\n"
"    color: #a0a0a0; /* Màu xám nhạt */")
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(390, 180, 291, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_2.setStyleSheet("border: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txt_email = QtWidgets.QLineEdit(parent=self.frame_2)
        self.txt_email.setGeometry(QtCore.QRect(10, 10, 271, 51))
        self.txt_email.setAccessibleName("")
        self.txt_email.setAccessibleDescription("")
        self.txt_email.setStyleSheet("    background-color: #f9f9f9;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    color: #333;")
        self.txt_email.setInputMask("")
        self.txt_email.setText("")
        self.txt_email.setObjectName("txt_email")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_3.setStyleSheet("border: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.txt_password = QtWidgets.QLineEdit(parent=self.frame_3)
        self.txt_password.setGeometry(QtCore.QRect(10, 0, 271, 51))
        self.txt_password.setAccessibleName("")
        self.txt_password.setAccessibleDescription("")
        self.txt_password.setStyleSheet("    background-color: #f9f9f9;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    color: #333;")
        self.txt_password.setInputMask("")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.btn_eye_p = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_eye_p.setGeometry(QtCore.QRect(220, 0, 61, 51))
        self.btn_eye_p.setStyleSheet("border: none;\n"
"background: none;")
        self.btn_eye_p.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/LeTien/python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon2)
        self.btn_eye_p.setIconSize(QtCore.QSize(32, 32))
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(170, 50, 121, 31))
        self.label.setStyleSheet("    color: #a0a0a0; /* Màu chữ xám nhạt */\n"
"    font-size: 14px;\n"
"    font-weight: normal;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "bạn mới biết điến shInk?"))
        self.btn_register.setText(_translate("MainWindow", "Signup"))
        self.google.setText(_translate("MainWindow", "Google"))
        self.facebook.setText(_translate("MainWindow", "Facebook"))
        self.label_4.setText(_translate("MainWindow", "or login with"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.label_5.setText(_translate("MainWindow", "Welcome Back"))
        self.label_6.setText(_translate("MainWindow", " Please login to your account"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "Forgot a pasword?"))
